FROM python:3.10

WORKDIR /app

COPY statistic_servise/src/ /app
COPY common /app/common
COPY common/statistic_grpc /app
COPY common/posts_grpc /app

WORKDIR /app

RUN pip install -r requirements.txt

ENV PYTHONPATH=/app
