# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistic.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstatistic.proto\x12\tstatistic\"\n\n\x08NoParams\"\x1e\n\x10GetByPostRequest\x12\n\n\x02id\x18\x01 \x01(\t\"1\n\x11GetByPostResponse\x12\r\n\x05likes\x18\x01 \x01(\x03\x12\r\n\x05views\x18\x02 \x01(\x03\"*\n\x15GetPopularPostRequest\x12\x11\n\tsort_type\x18\x01 \x01(\t\"<\n\nPostAnswer\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x03\"F\n\x16GetPopularPostResponse\x12,\n\rpopular_posts\x18\x01 \x03(\x0b\x32\x15.statistic.PostAnswer\"+\n\nUserAnswer\x12\x0e\n\x06\x61uthor\x18\x01 \x01(\t\x12\r\n\x05likes\x18\x02 \x01(\x03\"F\n\x16GetPopularUserResponse\x12,\n\rpopular_users\x18\x01 \x03(\x0b\x32\x15.statistic.UserAnswer2\x84\x02\n\x10StatisticService\x12O\n\x12GetStatisticByPost\x12\x1b.statistic.GetByPostRequest\x1a\x1c.statistic.GetByPostResponse\x12U\n\x0eGetPopularPost\x12 .statistic.GetPopularPostRequest\x1a!.statistic.GetPopularPostResponse\x12H\n\x0eGetPopularUser\x12\x13.statistic.NoParams\x1a!.statistic.GetPopularUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statistic_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NOPARAMS']._serialized_start=30
  _globals['_NOPARAMS']._serialized_end=40
  _globals['_GETBYPOSTREQUEST']._serialized_start=42
  _globals['_GETBYPOSTREQUEST']._serialized_end=72
  _globals['_GETBYPOSTRESPONSE']._serialized_start=74
  _globals['_GETBYPOSTRESPONSE']._serialized_end=123
  _globals['_GETPOPULARPOSTREQUEST']._serialized_start=125
  _globals['_GETPOPULARPOSTREQUEST']._serialized_end=167
  _globals['_POSTANSWER']._serialized_start=169
  _globals['_POSTANSWER']._serialized_end=229
  _globals['_GETPOPULARPOSTRESPONSE']._serialized_start=231
  _globals['_GETPOPULARPOSTRESPONSE']._serialized_end=301
  _globals['_USERANSWER']._serialized_start=303
  _globals['_USERANSWER']._serialized_end=346
  _globals['_GETPOPULARUSERRESPONSE']._serialized_start=348
  _globals['_GETPOPULARUSERRESPONSE']._serialized_end=418
  _globals['_STATISTICSERVICE']._serialized_start=421
  _globals['_STATISTICSERVICE']._serialized_end=681
# @@protoc_insertion_point(module_scope)
