# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: posts.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bposts.proto\x12\x05posts\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x01\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0c\n\x04\x62ody\x18\x04 \x01(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06status\x18\x06 \x01(\x03\"=\n\rCreateRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\"\x1c\n\x0e\x43reateResponse\x12\n\n\x02id\x18\x01 \x01(\t\",\n\rDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\x03\"&\n\x07GetById\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\"I\n\rUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0c\n\x04\x62ody\x18\x04 \x01(\t\"H\n\rGetAllRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x11\n\tpage_size\x18\x02 \x01(\x03\x12\x13\n\x0bpage_number\x18\x03 \x01(\x03\",\n\x0eGetAllResponse\x12\x1a\n\x05posts\x18\x01 \x03(\x0b\x32\x0b.posts.Post2\x9a\x02\n\x0cPostsService\x12\x39\n\nCreatePost\x12\x14.posts.CreateRequest\x1a\x15.posts.CreateResponse\x12\x33\n\nDeletePost\x12\x14.posts.DeleteRequest\x1a\x0f.posts.Response\x12*\n\x0bGetByIdPost\x12\x0e.posts.GetById\x1a\x0b.posts.Post\x12\x33\n\nUpdatePost\x12\x14.posts.UpdateRequest\x1a\x0f.posts.Response\x12\x39\n\nGetAllPost\x12\x14.posts.GetAllRequest\x1a\x15.posts.GetAllResponseB\x04Z\x02./b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'posts_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\002./'
  _globals['_POST']._serialized_start=56
  _globals['_POST']._serialized_end=184
  _globals['_CREATEREQUEST']._serialized_start=186
  _globals['_CREATEREQUEST']._serialized_end=247
  _globals['_CREATERESPONSE']._serialized_start=249
  _globals['_CREATERESPONSE']._serialized_end=277
  _globals['_DELETEREQUEST']._serialized_start=279
  _globals['_DELETEREQUEST']._serialized_end=323
  _globals['_RESPONSE']._serialized_start=325
  _globals['_RESPONSE']._serialized_end=351
  _globals['_GETBYID']._serialized_start=353
  _globals['_GETBYID']._serialized_end=391
  _globals['_UPDATEREQUEST']._serialized_start=393
  _globals['_UPDATEREQUEST']._serialized_end=466
  _globals['_GETALLREQUEST']._serialized_start=468
  _globals['_GETALLREQUEST']._serialized_end=540
  _globals['_GETALLRESPONSE']._serialized_start=542
  _globals['_GETALLRESPONSE']._serialized_end=586
  _globals['_POSTSSERVICE']._serialized_start=589
  _globals['_POSTSSERVICE']._serialized_end=871
# @@protoc_insertion_point(module_scope)
